//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21._106_10_Restoran.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int IdBooking { get; set; }
        public int IdTable { get; set; }
        public System.DateTime TimeOfBooking { get; set; }
        public int IdClient { get; set; }
        public string Comment { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Table Table { get; set; }
    }
}
